spring:
  application:
    name: api-gateway

  config:
    import: "configserver:http://localhost:8888"

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/